/**
 * Satu-satunya sumber ikon di web ini (Phosphor via react-icons, gaya bold membulat).
 * Aturan pakai:
 * - Pakai ikon hanya bila membantu: tombol tanpa teks, chip HUD, status, dan navigasi.
 * - Tanda centang (IconCheck, IconCheckCircle) hanya untuk arti "benar/selesai/terpilih".
 * - Jangan menambahkan ikon sparkle/kilau.
 * - Untuk identitas jalur, pakai ilustrasi di components/illustrations, bukan ikon.
 */
import type { IconType } from "react-icons";

export type { IconType };

export {
  PiAlarmBold as IconAlarm,
  PiArrowDownBold as IconArrowDown,
  PiArrowLeftBold as IconArrowLeft,
  PiArrowRightBold as IconArrowRight,
  PiArrowUpBold as IconArrowUp,
  PiArrowCounterClockwiseBold as IconRetry,
  PiBookOpenBold as IconBook,
  PiBriefcaseBold as IconBriefcase,
  PiBroomBold as IconBroom,
  PiCaretLeftBold as IconChevronLeft,
  PiCaretRightBold as IconChevronRight,
  PiChartBarBold as IconChartBar,
  PiChartLineBold as IconChartLine,
  PiChartPieBold as IconChartPie,
  PiChatCircleDotsBold as IconChat,
  PiCheckBold as IconCheck,
  PiCheckCircleBold as IconCheckCircle,
  PiClipboardTextBold as IconClipboard,
  PiClockBold as IconClock,
  PiCoffeeBold as IconCoffee,
  PiCoinsBold as IconCoins,
  PiCompassBold as IconCompass,
  PiCrosshairBold as IconCrosshair,
  PiDeviceMobileBold as IconPhone,
  PiDownloadSimpleBold as IconDownload,
  PiDropBold as IconDrop,
  PiExportBold as IconIosShare,
  PiFactoryBold as IconFactory,
  PiFileMagnifyingGlassBold as IconFileSearch,
  PiFireBold as IconFire,
  PiFlagBold as IconFlag,
  PiGameControllerBold as IconGamepad,
  PiGaugeBold as IconGauge,
  PiGearSixBold as IconSettings,
  PiGraduationCapBold as IconGraduation,
  PiHardDrivesBold as IconServer,
  PiHeartFill as IconHeart,
  PiInfoBold as IconInfo,
  PiKeyboardBold as IconKeyboard,
  PiLightbulbBold as IconIdea,
  PiLightningBold as IconBolt,
  PiListBold as IconMenu,
  PiLockBold as IconLock,
  PiMagnifyingGlassBold as IconSearch,
  PiMapTrifoldBold as IconMap,
  PiMedalBold as IconMedal,
  PiPackageBold as IconPackage,
  PiPauseBold as IconPause,
  PiPlayFill as IconPlay,
  PiQuestionBold as IconHelp,
  PiQuotesFill as IconQuote,
  PiScanBold as IconScan,
  PiShareNetworkBold as IconShare,
  PiShieldBold as IconShield,
  PiShieldWarningBold as IconThreat,
  PiSkullBold as IconSkull,
  PiSmileyBold as IconSmile,
  PiSpeakerHighBold as IconVolume,
  PiSpeakerSlashBold as IconMute,
  PiStarFill as IconStar,
  PiTimerBold as IconTimer,
  PiTrendDownBold as IconTrendDown,
  PiTrendUpBold as IconTrendUp,
  PiTrophyBold as IconTrophy,
  PiTruckBold as IconTruck,
  PiUserBold as IconUser,
  PiUsersBold as IconUsers,
  PiWalletBold as IconWallet,
  PiWarehouseBold as IconWarehouse,
  PiWarningBold as IconWarning,
  PiWindBold as IconWind,
  PiXBold as IconX,
  PiXCircleBold as IconXCircle,
} from "react-icons/pi";
