"use client";

import { useEffect, useMemo, type RefObject } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { clone as cloneSkeleton } from "three/examples/jsm/utils/SkeletonUtils.js";
import type { GameAvatarId } from "@/lib/types";

export type CharacterMotion = { phase: number; moving: boolean };

// Generated by tools/character/build_characters.py (Blender + MPFB); each file
// carries the rigged character and its Idle_Loop / Walk_Loop clips.
const characterUrl = (avatar: GameAvatarId) => `/characters/${avatar}.glb`;

// The models are real-world scale (~1.7 m); the campus is built a bit larger.
const WORLD_SCALE = 1.4;

function prepareMaterials(model: THREE.Object3D) {
  model.traverse((object) => {
    if (!(object instanceof THREE.Mesh)) return;
    object.castShadow = false;
    object.frustumCulled = false;
    const materials = Array.isArray(object.material) ? object.material : [object.material];
    for (const material of materials) {
      if (!(material instanceof THREE.MeshStandardMaterial)) continue;
      material.envMapIntensity = 0.6;
      // Hair, brows and lashes are alpha cards: alpha-testing them keeps them
      // sorted correctly against the head instead of flickering when blended.
      if (material.transparent) {
        material.transparent = false;
        material.alphaTest = 0.5;
        material.depthWrite = true;
        material.side = THREE.DoubleSide;
      }
    }
  });
}

function buildCharacter(scene: THREE.Group, clips: THREE.AnimationClip[]) {
  const model = cloneSkeleton(scene);
  model.scale.setScalar(WORLD_SCALE);
  prepareMaterials(model);

  const mixer = new THREE.AnimationMixer(model);
  const idle = clips.find((clip) => clip.name === "Idle_Loop");
  const walk = clips.find((clip) => clip.name === "Walk_Loop");
  if (!idle || !walk) throw new Error("The character asset is missing its idle or walk animation");
  const idleAction = mixer.clipAction(idle).play();
  const walkAction = mixer.clipAction(walk).play();
  walkAction.setEffectiveWeight(0);
  let walkWeight = 0;
  const update = (delta: number, moving: boolean) => {
    walkWeight = THREE.MathUtils.damp(walkWeight, moving ? 1 : 0, 9, delta);
    idleAction.setEffectiveWeight(1 - walkWeight);
    walkAction.setEffectiveWeight(walkWeight);
    mixer.update(delta * 1.35);
  };
  return { model, mixer, update };
}

export default function CharacterModel({
  avatar,
  motion,
}: {
  avatar: GameAvatarId;
  motion: RefObject<CharacterMotion>;
}) {
  const gltf = useGLTF(characterUrl(avatar));
  const character = useMemo(
    () => buildCharacter(gltf.scene, gltf.animations),
    [gltf.scene, gltf.animations],
  );
  useFrame((_, delta) => character.update(delta, motion.current.moving));

  useEffect(() => () => {
    character.mixer.stopAllAction();
    character.mixer.uncacheRoot(character.model);
  }, [character]);

  return <primitive object={character.model} />;
}
